apiVersion: v1
kind: Pod
metadata:
  name: midas-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: palantir-midas
      image: 10.101.10.244:5000/palantir-midas:1.0
      imagePullPolicy: Always
      env:
        # Kafka parameters
        - name: KAFKA_BROKERS_CSV
          value: "10.101.41.255:9092"
        - name: KAFKA_TOPIC_IN
          value: "netflow-anonymized-preprocessed"
        - name: KAFKA_TOPIC_OUT
          value: "netflow-ad-tba"
        # Kafka parameters for multi-tenancy
        - name: TENANT_SERVICE_API_URL
          value: "http://10.101.41.42:6000/api/partition"
        - name: TENANT_ID
          value: "ANY_TENANT"
        # MIDAS parameters
        - name: MIDAS_SLOT
          value: "1m"
        - name: MIDAS_THR
          value: "706206900"
        # Periodic re-training parameters
        - name: RETRAINING_PERIOD
          # value: "0" # DISABLED
          # value: "15" # 15 seconds
          # value: "30" # 30 seconds
          value: "86400" # 1 day (60*60*24 = 86400 seconds)
          # value: "2678400" # 1 month (60*60*24*31 = 2678400 seconds)
        - name: RETRAINING_DATA_HORIZON
          value: "30d" # 30d = last 30 days
        - name: OPENSEARCH_API_URL
          value: "10.101.41.42:9200"
        - name: OPENSEARCH_API_AUTH
          value: "admin:admin"
      volumeMounts:
        - name: midas-volume
          mountPath: /midas_volume
  volumes:
    - name: midas-volume
      hostPath:
        path: /media/palantir-nfs/NEC/volumes/midas
