apiVersion: v1
kind: Pod
metadata:
  name: midas
spec:
  restartPolicy: OnFailure
  containers:
    - name: palantir-midas
      image: 10.101.10.244:5000/palantir-midas:1.0
      imagePullPolicy: Always
      env:
        # Kafka parameters
        - name: KAFKA_BROKERS_CSV
          value: "10.101.41.255:9092"
        - name: KAFKA_TOPIC_IN
          value: "netflow-anonymized-preprocessed"
        - name: KAFKA_TOPIC_OUT
          value: "netflow-ad-tba"
        # Kafka parameters for multi-tenancy
        - name: TENANT_SERVICE_API_URL
          value: "http://10.101.41.42:6000/api/partition"
        - name: TENANT_ID
          value: "ANY_TENANT"
        # MIDAS parameters
        - name: MIDAS_SLOT
          value: "1m"
        - name: MIDAS_THR
          value: "706206900"
        # Periodic re-training parameters
        - name: RETRAINING_PERIOD
          value: "0"
        ### OpenSearch endpoint
        ### OpenSearch user/password
